<?php

namespace bedwars\manager;

use bedwars\events\PlayerListener;
use pocketmine\plugin\PluginBase;

class EventsManager extends Manager
{

    /**
     * @param PluginBase|null $plugin
     * @return void
     */
    public function init(?PluginBase $plugin): void
    {
        $plugin->getLogger()->info('a');
        $plugin->getServer()->getPluginManager()->registerEvents(new PlayerListener(), $plugin);
    }

    public function getPriority(): int
    {
        return ExtensionManager::PRIORITY_LOW; // TODO: Change the autogenerated stub
    }
}