<?php

namespace bedwars\manager;

use bedwars\game\Game;
use bedwars\game\GameOptions;
use pocketmine\plugin\PluginBase;

class GameManager extends Manager
{

    /** @var Game[] */
    public array $games = [];


    public function init(?PluginBase $plugin): void
    {
        $this->add('test', GameOptions::create()
        ->setMaxTeams(2)
        ->setPlayersPerTeam(2)
        ->setArena(ExtensionManager::getModule(ModulesIdentifier::ARENA_MANAGER)->getArenaByName('Test')));
    }

    /**
     * @param string $name
     * @param GameOptions $options
     * @return void
     */
    public function add(string $name, GameOptions $options): void
    {
        $this->games[$name] = new Game($name, $options);
    }

    /**
     * @param string $name
     * @return Game
     */
    public function get(string $name): Game
    {
        return $this->games[$name];
    }

    public function getPriority(): int
    {
        return ExtensionManager::PRIORITY_LOW; // TODO: Change the autogenerated stub
    }
}